### ISSUE TITLE
why use eval

### ISSUE THREAD

**Issue by steveoni** [mil-tokyo/sushi#31]
please , i want to know why most of the code is written in string in eval. i love the style of coding and am planning of implementing such method, but i dont know the reason it was used "eval" and "new function()"

**Comment by Kiikurage** [comment]
I'm not the author of the code, but I think that the author wanted to prevent to write the same code many times. JavaScript doesn't support operator overloading and implementing these operations as functions like `add` or `mul` needs a lot of duplicated codes. Generating such codes dynamically and evaluating by `eval` or `new Function()` keep code shorter.

**Comment by steveoni** [comment]
thanks
